BEGIN;

CREATE TABLE IF NOT EXISTS public.settings (
    key text PRIMARY KEY,
    value text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 120),
    phone text,
    email text,
    commission_type text CHECK (commission_type IN ('profit_pct', 'turnover_pct', 'flat')),
    commission_rate numeric(20,6) CHECK (commission_rate BETWEEN 0 AND 999999999999),
    notes text,
    active integer NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT clients_rule_pair CHECK ((commission_type IS NULL) = (commission_rate IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_clients_name_ci ON public.clients (lower(name));

CREATE TABLE IF NOT EXISTS public.uploads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name text NOT NULL,
    client_id bigint REFERENCES public.clients(id) ON DELETE SET NULL,
    filename text,
    platform text,
    ocr_text text,
    trade_count integer NOT NULL DEFAULT 0 CHECK (trade_count >= 0),
    submission_id uuid UNIQUE,
    submission_hash text,
    submission_owner text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uploads_receipt_pair CHECK (
        (submission_id IS NULL AND submission_hash IS NULL AND submission_owner IS NULL)
        OR (submission_id IS NOT NULL AND submission_hash IS NOT NULL AND submission_owner IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS public.trades (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    stock text NOT NULL CHECK (length(btrim(stock)) BETWEEN 1 AND 120),
    quantity numeric(20,6) NOT NULL CHECK (quantity > 0 AND quantity <= 999999999999),
    buy_price numeric(20,6) CHECK (buy_price BETWEEN 0 AND 999999999999),
    sell_price numeric(20,6) CHECK (sell_price BETWEEN 0 AND 999999999999),
    buy_date date,
    sell_date date,
    commission_override numeric(20,2) CHECK (commission_override BETWEEN 0 AND 999999999999),
    commission_type_snapshot text CHECK (commission_type_snapshot IN ('profit_pct', 'turnover_pct', 'flat')),
    commission_rate_snapshot numeric(20,6) CHECK (commission_rate_snapshot BETWEEN 0 AND 999999999999),
    source text NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'import', 'upload')),
    upload_id bigint REFERENCES public.uploads(id) ON DELETE SET NULL,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT trades_has_price CHECK (buy_price IS NOT NULL OR sell_price IS NOT NULL),
    CONSTRAINT trades_buy_pair CHECK ((buy_price IS NULL) = (buy_date IS NULL)),
    CONSTRAINT trades_sell_pair CHECK ((sell_price IS NULL) = (sell_date IS NULL)),
    CONSTRAINT trades_date_order CHECK (sell_date IS NULL OR buy_date IS NULL OR sell_date >= buy_date),
    CONSTRAINT trades_rule_snapshot_pair CHECK (
        (commission_type_snapshot IS NULL) = (commission_rate_snapshot IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS public.payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    amount numeric(20,2) NOT NULL CHECK (amount > 0 AND amount <= 999999999999),
    paid_on date NOT NULL,
    mode text,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.upload_assets (
    path text PRIMARY KEY CHECK (path ~ '^evidence/[0-9a-f]{32}\.(png|jpg|webp)$'),
    owner_hash text NOT NULL,
    scope_hash text NOT NULL,
    content_type text NOT NULL CHECK (content_type IN ('image/png', 'image/jpeg', 'image/webp')),
    byte_size bigint NOT NULL CHECK (byte_size > 0 AND byte_size <= 10485760),
    expires_at bigint NOT NULL,
    upload_id bigint REFERENCES public.uploads(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_trades_client ON public.trades(client_id);
CREATE INDEX IF NOT EXISTS idx_trades_dates ON public.trades(sell_date, buy_date);
CREATE INDEX IF NOT EXISTS idx_trades_upload ON public.trades(upload_id);
CREATE INDEX IF NOT EXISTS idx_payments_client ON public.payments(client_id);
CREATE INDEX IF NOT EXISTS idx_payments_date ON public.payments(paid_on);
CREATE INDEX IF NOT EXISTS idx_uploads_client ON public.uploads(client_id);
CREATE INDEX IF NOT EXISTS idx_assets_upload ON public.upload_assets(upload_id);
CREATE INDEX IF NOT EXISTS idx_assets_owner ON public.upload_assets(owner_hash, expires_at);

INSERT INTO public.settings(key,value) VALUES
    ('default_commission_type', 'profit_pct'),
    ('default_commission_rate', '10'),
    ('upload_code', ''),
    ('currency', chr(8377)),
    ('business_name', ''),
    ('upload_token', replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', ''))
ON CONFLICT (key) DO NOTHING;

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.uploads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.upload_assets ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.settings, public.clients, public.uploads, public.trades,
    public.payments, public.upload_assets FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.clients_id_seq, public.uploads_id_seq,
    public.trades_id_seq, public.payments_id_seq FROM PUBLIC, anon, authenticated;

INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
VALUES (
    'commission-evidence', 'commission-evidence', false, 10485760,
    ARRAY['image/png', 'image/jpeg', 'image/webp']
)
ON CONFLICT (id) DO UPDATE SET
    public = false,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

-- This restrictive policy also blocks accidental broad browser policies on a shared project.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname='storage' AND tablename='objects'
          AND policyname='commission_evidence_server_only'
    ) THEN
        CREATE POLICY commission_evidence_server_only ON storage.objects
            AS RESTRICTIVE FOR ALL TO anon, authenticated
            USING (bucket_id <> 'commission-evidence')
            WITH CHECK (bucket_id <> 'commission-evidence');
    END IF;
END;
$$;

COMMIT;
