BEGIN;

CREATE TABLE IF NOT EXISTS public.funds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id bigint NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    amount numeric(20,2) NOT NULL,
    added_on date NOT NULL,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_funds_client ON public.funds(client_id);
CREATE INDEX IF NOT EXISTS idx_funds_date ON public.funds(added_on);

ALTER TABLE public.funds ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.funds FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.funds_id_seq FROM PUBLIC, anon, authenticated;

COMMIT;
