CREATE TABLE IF NOT EXISTS public.client_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    stock TEXT NOT NULL,
    quantity NUMERIC,
    buy_price NUMERIC,
    added_on TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.client_shares ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all actions" ON public.client_shares FOR ALL USING (true);
